---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
    - example/**/*

Gemspec/AttributeAssignment:
  Enabled: false
